apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.logging.fluentd.name }}
  namespace: {{ .Values.logging.namespace }}
  labels:
    app: {{ .Values.logging.fluentd.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.logging.fluentd.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.logging.fluentd.name }}
    spec:
      serviceAccount: {{ .Values.logging.fluentd.name }}
      serviceAccountName: {{ .Values.logging.fluentd.name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Values.logging.fluentd.name }}
        image: {{ .Values.logging.fluentd.image }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers