apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:  
      - name: home
        image: home:1.0
        env:
            - name: roku_ip
              value: {{ .Values.app.env.roku_ip }}
            - name: hue_ip
              value: {{ .Values.app.env.hue_ip }}
            - name: hue_username
              value: {{ .Values.app.env.hue_username }}
        imagePullPolicy: Never
        ports:
        - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    service: {{ .Values.app.name }}
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: {{ .Values.app.name }}