apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.logging.fluentd.name }}
  namespace: {{ .Values.logging.namespace }}
  labels:
    app: {{ .Values.logging.fluentd.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.logging.fluentd.name }}
  labels:
    app: {{ .Values.logging.fluentd.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.logging.fluentd.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.logging.fluentd.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.logging.fluentd.name }}
  namespace: {{ .Values.logging.namespace }}